default:
  tags: ['docker']
  image: registry.gitlab.inria.fr/solverstack/docker/distrib
  before_script:
    - wget https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0-linux-x86_64.tar.gz
    - tar xvf cmake-3.22.0-linux-x86_64.tar.gz
    - export PATH="$PWD/cmake-3.22.0-linux-x86_64/bin/:$PATH"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_main
  - test_main

build_main:
  stage: build_main
  interruptible: true
  artifacts:
    name: scalfmm_build_main
    expire_in: 1 day
    paths:
      - build_main/
  script:
    - mkdir build_main && cd build_main && cmake ..
        -Dscalfmm_USE_MPI=OFF
        -Dscalfmm_BUILD_EXAMPLES=ON
        -Dscalfmm_BUILD_UNITS=ON
        -Dscalfmm_BUILD_TOOLS=ON
        -Dscalfmm_BUILD_CHECK=ON
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_CXX_COMPILER=g++
    - make -j5 2>&1 |tee scalfmm-main-build.log
    - make examples 2>&1 |tee scalfmm-main-examples-build.log
    - make units 2>&1 |tee scalfmm-main-units-build.log
  only:
    - main

test_main:
  stage: test_main
  interruptible: true
  dependencies:
    - build_main
  artifacts:
    name: scalfmm_main_test
    expire_in: 1 day
    paths:
      - build_main/
  script:
    - (cd build_main && OMP_NUM_THREADS=8 ctest --no-compress-output -VV -j 8
         -I 16,19,1 --repeat until-fail:10 --output-on-failure --stop-on-failure)
  only:
    - main
